[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.curl",
  "php82Extensions.openssl",
  "php82Extensions.gd",
  "php82Extensions.fileinfo"
]

[start]
cmd = "PHP_CLI_SERVER_WORKERS=8 php -d upload_max_filesize=10M -d post_max_size=12M -S 0.0.0.0:$PORT -t public"
