CREATE TABLE IF NOT EXISTS admin_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(120) NOT NULL,
  role VARCHAR(40) NOT NULL DEFAULT 'admin',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS requested_role VARCHAR(40) NOT NULL DEFAULT 'member';
ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS doctor_license_no VARCHAR(120) NULL;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE products ADD COLUMN IF NOT EXISTS name VARCHAR(190) NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS short_description TEXT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS hero_image VARCHAR(255) NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE products ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL;

SET @has_title := (
  SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'products' AND COLUMN_NAME = 'title'
);
SET @copy_title_sql := IF(@has_title > 0,
  'UPDATE products SET name = title WHERE (name IS NULL OR name = "")',
  'SELECT 1');
PREPARE copy_title_stmt FROM @copy_title_sql;
EXECUTE copy_title_stmt;
DEALLOCATE PREPARE copy_title_stmt;

CREATE TABLE IF NOT EXISTS clinics (
  id INT AUTO_INCREMENT PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS name VARCHAR(190) NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS address TEXT NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS province VARCHAR(120) NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS district VARCHAR(120) NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS phone VARCHAR(50) NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS hero_image VARCHAR(255) NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS logo_image VARCHAR(255) NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS map_url VARCHAR(255) NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS website_url VARCHAR(255) NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS facebook_url VARCHAR(255) NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS instagram_url VARCHAR(255) NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS tiktok_url VARCHAR(255) NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS line_id VARCHAR(120) NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS open_time TIME NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS close_time TIME NULL;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL;

CREATE TABLE IF NOT EXISTS clinic_products (
  clinic_id INT NOT NULL,
  product_id INT NOT NULL,
  PRIMARY KEY (clinic_id, product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS doctors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name_th VARCHAR(190) NOT NULL,
  name_en VARCHAR(190) NULL,
  specialty VARCHAR(190) NOT NULL,
  clinic_name VARCHAR(190) NOT NULL,
  phone VARCHAR(50) NULL,
  email VARCHAR(190) NULL,
  bio TEXT NULL,
  photo VARCHAR(255) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS news_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NOT NULL,
  category VARCHAR(40) NOT NULL DEFAULT 'news',
  summary TEXT NULL,
  hero_image VARCHAR(255) NULL,
  views INT NOT NULL DEFAULT 0,
  published_at DATETIME NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS videos (
  id INT AUTO_INCREMENT PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS title VARCHAR(220) NULL;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS description TEXT NULL;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS detail_summary TEXT NULL;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS detail_content LONGTEXT NULL;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS video_url VARCHAR(255) NULL;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS thumbnail VARCHAR(255) NULL;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS platform VARCHAR(40) NOT NULL DEFAULT 'tiktok';
ALTER TABLE videos ADD COLUMN IF NOT EXISTS access_level VARCHAR(20) NOT NULL DEFAULT 'public';
ALTER TABLE videos ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL;

CREATE TABLE IF NOT EXISTS home_slides (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NULL,
  desktop_image VARCHAR(255) NULL,
  mobile_image VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS website_product_gallery (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NULL,
  image_path VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS website_product_groups (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NULL,
  image_path VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contact_messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  email VARCHAR(190) NOT NULL,
  phone VARCHAR(50) NULL,
  subject VARCHAR(220) NOT NULL,
  message TEXT NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'new',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
